### ISSUE TITLE
Additional commands

### ISSUE THREAD

**Issue by garbled1** [ccutrer/balboa_worldwide_app#1]
I don't have another way of contacting you really, so..

	{ 0x0A, 0xBF, 0x22 }, /* BMTS_PANEL_REQ */
Can you try sending:
7E080ABF22XX00YYCK7E
where: CK checksum.  XX,YY is one of:
00 01
02 00
04 00

And maybe a few other values too if you want.  I got some odd responses, and some interesting ones.  Namely, 00/01 gave me a much better config status, and 02/00 gave me the model number, version, and some other version info encoded in hex.  I'd like to see your data to see if I can decode it properly.  Here is mine:

0,1 - 7E0B0ABF2E 0A0001500000BF7E
2,0 - 7E1A0ABF24 64DC140042503230303047310451800C6B010A0200F97E
4,0 - 7E0E0ABF25 120432635068290341197E

This was my reply from 00/01
SZ 02 03 04   05 06 07 08 09 10 CB
0B 0A BF 2E   0A 00 01 50 00 00 BF

05 - nrof pumps. Bitmask 2 bits per pump.
06 - P6xxxxP5
07 - L2xxxxL1
08 - CxxxxxBL - circpump, blower
09 - xxMIxxAA - mister, Aux2, Aux1

**Comment by ccutrer** [comment]
0,1: 7e0b0abf2e0a0001d00000b47e
2,0: 7e1a0abf2464dc11004246425032302020013d12382e010a04009b7e
4,0: 7e0e0ab25040132635068690341547e

breaking down 0,1:
SZ 02 03 04 05 06 07 08 09 10 CB
0B 0A BF 2E 0A 00 01 D0 00 00 B4

I differ in byte 8. you have 50, I have D0.
