### ISSUE TITLE
Does this allow you to set values, or simply read?

### ISSUE THREAD

**Issue by yetdog** [ccutrer/balboa_worldwide_app#11]
It seems like this Ruby gem queries the Spa and then publishes the resulting data (temp, pump status, etc) to the MQTT broker. 

Does it also listen to that same MQTT broker on particular topics for SET commands, and then turn around and set temperature, turn on pumps, etc? I'm not seeing that, from digging through the code...

HomeAssistant & MQTT user hoping to integrate my Tub with this...

**Comment by ccutrer** [comment]
Yes, it does. The short version is every property subscribed to a /set topic as well. The topics are self-describing. See https://homieiot.github.io/ for the standard it follows.
