### ISSUE TITLE
Process takes ~100% cpu 

### ISSUE THREAD

**Issue by konsulten** [ccutrer/balboa_worldwide_app#18]
Current platform where Im running it is a raspberry pi 3 +. Directly after starting it takes up 100% cpu and stays there. Question is if there is some while loop without proper sleep or something missing?

**Comment by konsulten** [comment]
It seems like its in the poll function in client, if read is used it does not block until data is available. and thus spinning on reading 0 bytes. Added a if @buffer.length = 0 sleep (0.1) end which seems to have done the trick

**Comment by ccutrer** [comment]
Were you using the master branch when you reported this, and using RS-485? If not, you should either do that, or update to the 1.2.0 release which I just pushed. There were problems with the old serial library that it would return immediately when there was no data. I switch the serial library backend and it fixed the problem. It's been running for months at my house with no issues; I apologize for not getting around to releasing a new version.

**Comment by konsulten** [comment]
I were using the master branch when I reported  this. Will check if it was
any updates with your 1.2.0 rel.
mån 21 dec. 2020 kl. 17:41 skrev Cody Cutrer <notifications@github.com>:

**Comment by ccutrer** [comment]
Serial or WiFi?

**Comment by konsulten** [comment]
Oh, sorry. Rs-485

mån 21 dec. 2020 kl. 18:10 skrev Cody Cutrer <notifications@github.com>:
