### ISSUE TITLE
RS485 Connection

### ISSUE THREAD

**Issue by JochenKoehler69** [ccutrer/balboa_worldwide_app#34]
Our spa was just delivered and I wonder were the RS485 adapter could be connected.
- There is a connector for the WLAN module just on the board
- There is a cable for a second control display
Which one is correct?

Thanks for help.

**Comment by EricAgostinelli** [comment]
> 
> 
> Finally it's running !!! Some extra settings in the system and in the "systemd" file were necessary to make it executable. However I had to do two additions in the source code:
> 
>     * In client.rb "require 'uri' has" to be added
> 
>     * In bwa_mqtt_bridge "require 'set'" has to be added
> 
> 
> May be you could add this to your code. I habe Ruby 3.0.0 installed.
> 
> If it is of any interest I could contribute with a small description about how I made it up and running on the raspberry ...
> 
> Thanks a lot for your support and the great script :-)

Would be great to see a how to/tutorial/walk through for 485 Communication.
