### ISSUE TITLE
Modifying filter-cycles

### ISSUE THREAD

**Issue by JochenKoehler69** [ccutrer/balboa_worldwide_app#37]
I try to enhance the code to be able to modify the filter cycles.
The easy part was to read out the data and send it to the MQTT broker.
But I haven't understood yet the mechanism to send modified date back to the bwa.
Could you please give me a short explanation how this is working?
Thanks.

**Comment by BowenMarmot** [comment]
See my patch attached to issue: #38 

I developed the code in march and have been using it on my spa since then.

**Comment by JochenKoehler69** [comment]
@BowenMarmot thanks for your answer.
I'm just figuring out to test your code and merge it with the newest version - and pulling it to git ...

**Comment by JochenKoehler69** [comment]
@BowenMarmot Just added your code to the fork https://github.com/JochenKoehler69/balboa_worldwide_app and will do a pull request ...

**Comment by ccutrer** [comment]
PR is merged.
