### ISSUE TITLE
Control of lights 

### ISSUE THREAD

**Issue by JochenKoehler69** [ccutrer/balboa_worldwide_app#48]
This is a minor issue, however - I'm wondering if it's possible to control the lights? Any Idea?

**Comment by ccutrer** [comment]
Turning lights on and off works fine for me. Are you saying set them to a specific color? There's no direct way to do it, but I have a theory that you can get to a specific style by by rapidly turning the lights off and on a set number of times. I've not cared enough to explore it though.
