### ISSUE TITLE
Patent for a "Method and system for testing spas"

### ISSUE THREAD

**Issue by einkvan** [ccutrer/balboa_worldwide_app#6]
Perhaps this Balboa patent contains relevant information on how to decode the TTL side of the interface.

It describes a test setup for Balboa controlled spas, and the configuration indicates 7 different models around year 2003. Maybe the internal control protocol has not changed that much...

https://www.google.com/patents/US7158909

Thanks for your efforts so far. Myself I just realized after buying that I need an internet control for the spa. It has a Balboa GS510Z controller with VL801 panel. There is no Wifi  module or BWA for that, so I look for a way to interface directly on the SPI bus in order to connect an IoT device, and hopefully a mobile app that communicates with that over the internet.

**Comment by ccutrer** [comment]
I actually looked through that patent last night. It has some interesting info, but does not have any details on the protocol itself.
