### ISSUE TITLE
Service dont start.

### ISSUE THREAD

**Issue by IkaSGC** [ccutrer/balboa_worldwide_app#62]
Hi, I got here from the following link.

https://community.home-assistant.io/t/balboa-hot-tub-spa-automation-and-power-savings/353032

I did the installation and edited the file, so that it has the IP of my MQTT and serial port (BT should be disabled):

"ExecStart=/usr/local/bin/bwa_mqtt_bridge mqtt://192.168.x.x/ /dev/ttyAMA0"

But when I start the service, an error pops up.

"bwa_mqtt_bridge.service: Failed to determine user credentials: No such process"
"bwa_mqtt_bridge.service: Failed at step USER spawning /usr/local/bin/bwa_mqtt_bridge: No such process"

Do you happen to know where the problem is?

**Comment by ccutrer** [comment]
It sounds like maybe the user you have the service to run as doesn't exist on your system.

**Comment by IkaSGC** [comment]
If I may ask, basically the installation should be like this:

1) sudo curl https://github.com/ccutrer/balboa_worldwide_app/raw/main/contrib/bwa_mqtt_bridge.service -L -o /etc/systemd/system/bwa_mqtt_bridge.service

2) Edit configuration (HomeAssistent MQTT IP address) and serial port settings (USB device or ttyAMA0 / ttyS0)

3) Start the service and everything should tread, right?

**Comment by IkaSGC** [comment]
Ok, I screwed up. I skipped part of the "ruby" installation. So I fixed that, but the "balboa_worldwide_app" installation doesn't work.

-----------------------------------
ERROR:  Error installing balboa_worldwide_app:
        ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.7.0/gems/digest-crc-0.6.4/ext/digest
/usr/bin/ruby2.7 -I/usr/lib/ruby/vendor_ruby -rrubygems /usr/share/rubygems-integration/all/gems/rake-13.0.3/exe/rake RUBYARCHDIR\=/var/lib/gems/2.7.0/extensions/arm-linux/2.7.0/digest-crc-0.6.4 RUBYLIBDIR\=/var/lib/gems/2.7.0/extensions/arm-linux/2.7.0/digest-crc-0.6.4
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

You might have to install separate package for the ruby development
environment, ruby-dev or ruby-devel for example.

rake failed, exit code 1

**Comment by IkaSGC** [comment]
Well, I guess I made progress in my research. Much more needs to be installed:

- sudo curl https://github.com/ccutrer/balboa_worldwide_app/raw/main/contrib/bwa_mqtt_bridge.service -L -o /etc/systemd/system/bwa_mqtt_bridge.service
- sudo apt install ruby
- sudo apt-get install ruby-dev
- Restart
- gem install balboa_worldwide_app

- Edit the config file (set the IP MQTT, Device and change User to "pi"): sudo nano /boot/config.txt
- sudo systemctl enable bwa_mqtt_bridge
- sudo systemctl start bwa_mqtt_bridge

I now end up on:

"Job for bwa_mqtt_bridge.service failed because a timeout was exceeded."

I don't know what timeout it is, but I'm not home now, so the connection with HA has no way to establish it. I'll test how I'll be home.

**Comment by tortho** [comment]
I encounter the exact same issue.
Did you manage to get it going?

Is there any setting we can do with debug and verbose to get some information?
