### ISSUE TITLE
Hot Tub Configuration

### ISSUE THREAD

**Issue by supersebbo** [ccutrer/balboa_worldwide_app#72]
Hi,

I'm hoping to get this deployed on my Balboa BP2100 system tomorow, thanks for all your hard work here. 

One question - you mentioned in the Git readme that it assumes a default config of 2 two-speed pumps etc.  Is it required (possible?) to change this config if your tub has a different config?  My tub has:
2 x 1-Speed Pump
1 x Circ Pump
1 x Ozone Generator 
1 x Heater
1 x Lights Circuit

Is there a config file to edit to match with the physical config?

Thanks!

**Comment by ccutrer** [comment]
Your config should be detected just fine. I updated the readme to reflect that auto-detection happens now.
