### ISSUE TITLE
Unknown Bus packages

### ISSUE THREAD

**Issue by Arut42** [ccutrer/balboa_worldwide_app#8]
between the known packets, unknown packets appear regularly more often than known ones.
I am directly over rs485 at the bus.

7E 05 11 BF 06 37 7E
7E 05 12 BF 06 8A 7E
7E 05 12 BF 07 8D 7E
7E 05 13 BF 06 E1 7E
7E 05 14 BF 06 F7 7E
7E 05 FE BF 00 AC 7E
7E 05 15 BF 06 9C 7E
7E 05 16 BF 06 21 7E
7E 05 17 BF 06 4A 7E
7E 05 18 BF 06 0D 7E
7E 05 19 BF 06 66 7E
7E 05 1A BF 06 DB 7E
7E 05 1B BF 06 B0 7E
7E 05 10 BF 06 5C 7E

does anyone know what that is?
looks like packages without content to me.

7E Start
05 Message Length
10 Message Type
BF Message Type
06 Message Type
5C CRC
7E Stop

**Comment by ccutrer** [comment]
10 BF 06 is "ready to receive command". I suspect most of the XX BF 06 are the same, with the first byte being different device types/IDs. I'm just ignoring them all. It's a _very_ chatty bus.
